sonar.sources=.
sonar.scanner.keepReport=true

#Cloud configuration
sonar.organization=kev-test
sonar.projectKey=kev-test_kev-testing
sonar.scanner.sonarcloudUrl=https://dev17.sc-dev17.io
sonar.scanner.apiBaseUrl=https://api.sc-dev17.io
#sonar.scanner.engineJarPath=/Users/kevin.tang/IdeaProjects/sonar-scanner-engine/cloud/sonar-scanner-engine/build/libs/scanner-engine-cloud-12.29-SNAPSHOT-all.jar